version: '3.4'

services:
  db:
     image: calculadora-rest-db
     command: mysqld --default-authentication-plugin=mysql_native_password
     restart: always
     build:
       context: .
       dockerfile: db/Dockerfile
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
       MYSQL_DATABASE: restbd
     ports:
       - "5859:3306"
     networks:
       - "udemy-network"
  calculadora-rest:
    image: calculadora-rest
    build:
      context: .
      dockerfile: CalculadoraRest/Dockerfile
    environment:
       TZ: America/Sao_Paulo
       ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "44236:80"
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge