sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd 03_CalculadoraRest/CalculadoraRest/
  - echo "Ok"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag calculadora-rest:latest $DOCKER_USERNAME/calculadora-rest:$TRAVIS_JOB_ID;
    docker tag calculadora-rest-db:latest $DOCKER_USERNAME/calculadora-rest-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/calculadora-rest:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/calculadora-rest-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false